name: Test React app
on: workflow_dispatch
jobs: 
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Code
              uses: actions/checkout@v4
            - name: Install Node v18
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install
              run: npm install
            - name: Test
              run: npm run test
